/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.delor.graphprocessing;

import java.awt.image.BufferedImage;
import static pl.delor.graphprocessing.GP.copyImage;

/**
 *
 * @author delor
 */
public abstract class JPreviewPanel extends javax.swing.JPanel {

    /**
     * Creates new form JPreviewPanel
     */
    private JPreview viewParent = null;

    public JPreview getParent() {
        return viewParent;
    }

    public void setParent(JPreview parent) {
        this.viewParent = parent;
    }

    public JPreviewPanel() {
        initComponents();
    }

    protected abstract String title();

    protected void processImage() {
        this.setImageOutput(doProcessImage(copyImage(getImageInput()), getImageOutput()));
    }

    protected abstract BufferedImage doProcessImage(BufferedImage input, BufferedImage output);

    public BufferedImage getImageInput() {
        return this.viewParent.getImageSource();
    }

    public BufferedImage getImageOutput() {
        return this.viewParent.getImageOutput();
    }

    public void setImageOutput(BufferedImage i) {
        this.viewParent.setImageOutput(i);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
