package pl.delor.graphprocessing;
import java.util.Dictionary;
import java.util.Hashtable;
import java.awt.image.BufferedImage;
import static pl.delor.graphprocessing.GP.getBlue;
import static pl.delor.graphprocessing.GP.getGreen;
import static pl.delor.graphprocessing.GP.getRed;
import static pl.delor.graphprocessing.GP.toRGB;
import java.awt.Component;
import javax.swing.JLabel;
/**
 *
 * @author delor
 */
public class JPreviewPanelHistExtend extends JPreviewPanel {

    /**
     * Creates new form JPreviewPanelHistExtend
     */
    public JPreviewPanelHistExtend() {
        initComponents();
        
        Dictionary<Integer, Component> labelTable = new Hashtable<Integer, Component>();
        
        labelTable.put(0, new JLabel("0"));
        labelTable.put(50, new JLabel("50"));
        labelTable.put(100, new JLabel("100"));
        labelTable.put(150, new JLabel("150"));
        labelTable.put(200, new JLabel("200"));
        labelTable.put(255, new JLabel("Max"));

        rangeSliderHistExt.setLabelTable(labelTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rangeSliderHistExt = new pl.delor.graphprocessing.RangeSlider();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        rangeSliderHistExt.setMajorTickSpacing(25);
        rangeSliderHistExt.setMaximum(255);
        rangeSliderHistExt.setPaintLabels(true);
        rangeSliderHistExt.setPaintTicks(true);
        rangeSliderHistExt.setUpperValue(150);
        rangeSliderHistExt.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rangeSliderHistExtStateChanged(evt);
            }
        });
        add(rangeSliderHistExt);
    }// </editor-fold>//GEN-END:initComponents

    private void rangeSliderHistExtStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rangeSliderHistExtStateChanged
        super.processImage();
    }//GEN-LAST:event_rangeSliderHistExtStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pl.delor.graphprocessing.RangeSlider rangeSliderHistExt;
    // End of variables declaration//GEN-END:variables

    @Override
    protected String title() {
        return "Histogram Normalization";
    }

    @Override
    protected BufferedImage doProcessImage(BufferedImage input, BufferedImage output) {
        int min = rangeSliderHistExt.getValue();
        int max = rangeSliderHistExt.getUpperValue();
        for (int y = 0; y < input.getHeight(); y++) {
            for (int x = 0; x < input.getWidth(); x++) {
                int pixel = input.getRGB(x, y);
                int r = (getRed(pixel) - min) * 255/(max - min);
                int g = (getGreen(pixel) - min) * 255/(max - min);
                int b = (getBlue(pixel) - min) * 255/(max - min);
                output.setRGB(x, y, toRGB(r, g, b));
            }
        }
        return output;
    }

}
