/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.delor.graphprocessing;
import java.awt.image.BufferedImage;
import static pl.delor.graphprocessing.GP.getBlue;
import static pl.delor.graphprocessing.GP.getGreen;
import static pl.delor.graphprocessing.GP.getRed;
import static pl.delor.graphprocessing.GP.toRGB;

/**
 *
 * @author delor
 */
public class JPreviewPanelGamma extends JPreviewPanel {

    /**
     * Creates new form JPreviewPanelPower
     */
    public JPreviewPanelGamma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSliderPower = new javax.swing.JSlider();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jSliderPower.setMajorTickSpacing(1);
        jSliderPower.setMaximum(5);
        jSliderPower.setMinimum(1);
        jSliderPower.setPaintLabels(true);
        jSliderPower.setPaintTicks(true);
        jSliderPower.setValue(1);
        jSliderPower.setRequestFocusEnabled(false);
        jSliderPower.setValueIsAdjusting(true);
        jSliderPower.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderPowerStateChanged(evt);
            }
        });
        add(jSliderPower);
    }// </editor-fold>//GEN-END:initComponents

    private void jSliderPowerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderPowerStateChanged
        super.processImage();
    }//GEN-LAST:event_jSliderPowerStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider jSliderPower;
    // End of variables declaration//GEN-END:variables

    @Override
    protected String title() {
        return "Gamma correction";
    }

    @Override
    protected BufferedImage doProcessImage(BufferedImage input, BufferedImage output) {
        int p = jSliderPower.getValue();
        for (int y = 0; y < input.getHeight(); y++) {
            for (int x = 0; x < input.getWidth(); x++) {
                int pixel = input.getRGB(x, y);
                int r = (int)(255 * Math.pow(getRed(pixel)/255.0, 1.0/p));
                int g = (int)(255 * Math.pow(getGreen(pixel)/255.0, 1.0/p));
                int b = (int)(255 * Math.pow(getBlue(pixel)/255.0, 1.0/p));

                output.setRGB(x, y, toRGB(r, g, b));
            }
        }
        return output;
    }

}
