package pl.delor.graphprocessing;

import java.awt.Dialog;
import java.awt.Frame;
import java.awt.image.BufferedImage;
import static pl.delor.graphprocessing.GP.copyImage;

/**
 *
 * @author delor
 */
public class JPreview extends javax.swing.JDialog {
    

    enum STATUS {
        NONE, OK, CANCEL
    };
    /**
     * Creates new form JPreview
     */
    private STATUS _exit = STATUS.NONE;

    BufferedImage imageSource = null;

    public BufferedImage getImageSource() {
        return imageSource;
    }
    BufferedImage imageOutput = null;

    protected void setImageOutput(BufferedImage imageOutput) {
        this.imageOutput = imageOutput;
        jImagePreview.setImage(this.imageOutput);
    }

    public BufferedImage getImageOutput() {
        return imageOutput;
    }

    @Override
    public void setTitle(String title) {
        super.setTitle("Preview - " + title);
    }

    public JPreview(Frame parent, BufferedImage image, JPreviewPanel panel) {
        super(parent);

        _exit = STATUS.NONE;
        this.imageSource = copyImage(image);
        this.imageOutput = copyImage(image);

        initComponents();
        panel.setParent(this);
        jPanelParameters.add(panel);

        this.setTitle(panel.title());

        panel.processImage();

        this.revalidate();
        this.repaint();
        pack();
        setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
        this.setVisible(true);
    }

    public STATUS getExitStatus() {
        return this._exit;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jImagePreview = new pl.delor.graphprocessing.JImage();
        jPanelParameters = new javax.swing.JPanel();
        jPanelButtons = new javax.swing.JPanel();
        jButtonOk = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(59, 28));
        setPreferredSize(new java.awt.Dimension(271, 291));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jImagePreview.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jImagePreviewLayout = new javax.swing.GroupLayout(jImagePreview);
        jImagePreview.setLayout(jImagePreviewLayout);
        jImagePreviewLayout.setHorizontalGroup(
            jImagePreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jImagePreviewLayout.setVerticalGroup(
            jImagePreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 285, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jImagePreview, gridBagConstraints);

        jPanelParameters.setLayout(new java.awt.GridLayout(1, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jPanelParameters, gridBagConstraints);

        jPanelButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 5));

        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });
        jPanelButtons.add(jButtonOk);

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanelButtons.add(jButtonCancel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jPanelButtons, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        _exit = STATUS.OK;
        this.setVisible(false);
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        _exit = STATUS.CANCEL;
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private pl.delor.graphprocessing.JImage jImagePreview;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelParameters;
    // End of variables declaration//GEN-END:variables
}
