/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.delor.graphprocessing;

import java.awt.Dialog;
import java.awt.Frame;
import java.awt.image.BufferedImage;

/**
 *
 * @author delor
 */
public abstract class JPreview extends javax.swing.JDialog {

    enum STATUS { NONE, OK, CANCEL };
    /**
     * Creates new form JPreview
     */
    private STATUS _exit = STATUS.NONE;
    
    BufferedImage imageSource = null;

    public BufferedImage getImageSource() {
        return imageSource;
    }
    BufferedImage imageOutput = null;

    protected void setImageOutput(BufferedImage imageOutput) {
        this.imageOutput = imageOutput;
        jImagePreview.setImage(this.imageOutput);
    }
    
    public BufferedImage getImageOutput(){
        return imageOutput;
    }
    @Override
    public void setTitle(String title){
        super.setTitle("Preview - " + title);
    }
    private JPreview() {
        initComponents();
    }
    public JPreview(Frame parent, BufferedImage image) {
        super(parent);
        initComponents();
        
        this.setTitle(title());
        
        this.imageSource = image;
        this.imageOutput = image;
                
        this.processImage();
        
        this.pack();
        setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
        this.setVisible(true);
    }
    
    protected abstract void processImage();
    protected abstract String title();
    
    public STATUS getExitStatus(){
        return this._exit;
    }
    
    public static int getRed(int pixel){
        return (pixel << 8) >>> 24 ;
    }
    public static int getGreen(int pixel){
        return (pixel << 16) >>> 24;
    }
    public static int getBlue(int pixel){
        return (pixel << 24) >>> 24;
    }
    public static int toRGB(int r, int g, int b){
        return (((r << 8) | g) << 8) | b;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jImagePreview = new pl.delor.graphprocessing.JImage();
        jPanel1 = new javax.swing.JPanel();
        jButtonOk = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(59, 28));
        setPreferredSize(new java.awt.Dimension(200, 220));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jImagePreview.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jImagePreviewLayout = new javax.swing.GroupLayout(jImagePreview);
        jImagePreview.setLayout(jImagePreviewLayout);
        jImagePreviewLayout.setHorizontalGroup(
            jImagePreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jImagePreviewLayout.setVerticalGroup(
            jImagePreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jImagePreview, gridBagConstraints);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 5));

        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonOk);

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        _exit = STATUS.OK;
        this.setVisible(false);
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        _exit = STATUS.CANCEL;
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private pl.delor.graphprocessing.JImage jImagePreview;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
