/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.delor.graphprocessing;

import java.awt.image.BufferedImage;
import static pl.delor.graphprocessing.GP.getBlue;
import static pl.delor.graphprocessing.GP.getGreen;
import static pl.delor.graphprocessing.GP.getRed;
import static pl.delor.graphprocessing.GP.toRGB;

/**
 *
 * @author delor
 */
public class JPreviewPanelBrightness extends JPreviewPanel {

    /**
     * Creates new form JPreviewPanelTest
     */
    public JPreviewPanelBrightness() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setName(""); // NOI18N
        setLayout(new java.awt.BorderLayout());

        jSlider1.setMaximum(255);
        jSlider1.setMinimum(-255);
        jSlider1.setValue(0);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        add(jSlider1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        super.processImage();
    }//GEN-LAST:event_jSlider1StateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables

    @Override
    protected String title() {
        return "Test!";
    }

    @Override
    protected BufferedImage doProcessImage(BufferedImage input, BufferedImage output) {
        int rozjasnienie = jSlider1.getValue();
        for (int y = 0; y < input.getHeight(); y++) {
            for (int x = 0; x < input.getWidth(); x++) {
                int pixel = input.getRGB(x, y);
                int r = getRed(pixel) + rozjasnienie;
                int g = getGreen(pixel) + rozjasnienie;
                int b = getBlue(pixel) + rozjasnienie;

                if (r > 255) {
                    r = g = b = 255;
                }
                if (g > 255) {
                    r = g = b = 255;
                }
                if (b > 255) {
                    r = g = b = 255;
                }

                output.setRGB(x, y, toRGB(r, g, b));
            }
        }
        return output;
    }

}
