/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.delor.graphprocessing;

import java.awt.Frame;
import java.awt.image.BufferedImage;

/**
 *
 * @author delor
 */
public class JPreviewToGray extends JPreview {

    /**
     * Creates new form JPreviewToGray
     * @param parent
     * @param image
     */
    public JPreviewToGray(Frame parent, BufferedImage image) {
        super(parent, image);
    }
    
    @Override
    protected void processImage(){
        BufferedImage out = this.getImageOutput();
        for(int y = 0; y < out.getHeight(); y++)
            for(int x = 0; x < out.getWidth(); x++){
                int pixel = out.getRGB(x, y);
                int r = getRed(pixel);
                int g = getGreen(pixel);
                int b = getBlue(pixel);
                int srednia = (int)((r + g + b)/3.0);
                int pixelSzary = toRGB(srednia, srednia, srednia);
                out.setRGB(x, y, pixelSzary);
            }
        this.setImageOutput(out);
    }
    @Override
    protected String title() {
        return "To gray";
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
